export default {
  main: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
  },
  travellerCardsWrapper: {
    marginTop: 16,
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 12,
  },
  cardWrapper: {
    boxShadow: '0 2px 10px rgba(0, 0, 0, 0.08)',
    borderRadius: 14,
    width: '90%',
    display: 'flex',
    flexDirection: 'column',
    padding: 16,
    backgroundColor: 'white',
  },
  cardTopRow: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
  },
  imgWrapper: {
    position: 'relative',
    flexShrink: 0,
  },
  img: {
    width: 56,
    height: 56,
    borderRadius: '50%',
    objectFit: 'cover',
  },
  infoWrapper: {
    flex: 1,
    marginLeft: 14,
    minWidth: 0,
  },
  nameRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
  },
  name: {
    fontSize: 15,
    fontWeight: 600,
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  currentCity: {
    fontSize: 12.5,
    color: '#888',
    marginTop: 2,
  },
  bio: {
    fontSize: 12.5,
    color: '#666',
    marginTop: 10,
    lineHeight: 1.4,
  },
  statusDot: {
    position: 'absolute',
    bottom: 2,
    right: 2,
    width: 12,
    height: 12,
    borderRadius: '50%',
    border: '2px solid white',
  },
  chatButtonWrapper: {
    position: 'relative',
    flex: 1,
  },
  chatUnreadBadge: {
    position: 'absolute',
    top: -4,
    right: -4,
    width: 12,
    height: 12,
    borderRadius: '50%',
    border: '2px solid white',
    backgroundColor: '#ff3b30',
    pointerEvents: 'none',
  },
  statusLabel: {
    fontSize: 11,
    fontWeight: 600,
    padding: '2px 8px',
    borderRadius: 20,
  },
  actionsRow: {
    display: 'flex',
    flexDirection: 'row',
    gap: 8,
    marginTop: 14,
  },
};
